### ISSUE TITLE
Extra white path

### ISSUE THREAD

**Issue by snelsi** [devias-io/untitled-ui#1]
A lot of react icons have an extra `path fill="#fff" fillOpacity={0.01}` inside of them. 
Is this intentional? Looks like an export artifact or something.

For example, clock icon:
![image](https://github.com/devias-io/untitled-ui/assets/15171036/0abe7c7a-e95a-4d2f-b397-70b09b2719d8)

You should probably remove them.

**Comment by acomanescu** [comment]
@snelsi The icons are generated from the svg files. We have two options.

First would be to remove the styling attributes (fill and fill opacity) and re-export the svg files from Figma, then regenerate & build the jsx files. Second option, leave the svg files as they are and remove the props using the svgo plugins. 

The second option is quicker but might introduce unexpected bugs.

**Comment by snelsi** [comment]
I think the simplest solution is to write a regex to match path tags with fill="white" and remove them quickly in VS Code

**Comment by acomanescu** [comment]
Fixed an released in v0.1.2
