### ISSUE TITLE
Request for new icons support

### ISSUE THREAD

**Issue by ayush6160** [devias-io/untitled-ui#7]
It will be a huge help if you can update the package with the newer icons like Cars01

**Comment by acomanescu** [comment]
Hi @ayush6160 . I've deployed a new release 0.1.3 and it should include the missing icons. If you notice any issues, please let me know.

**Comment by ayush6160** [comment]
> Hi @ayush6160 . I've deployed a new release 0.1.3 and it should include the missing icons. If you notice any issues, please let me know.

Thank you! Working perfectly
