### ISSUE TITLE
Cannot change stroke width

### ISSUE THREAD

**Issue by tom-ads** [devias-io/untitled-ui#8]
How can you change the icon stroke width?

I've tried:

`<SearchIcon strokeWidth={1} />`

`<SearchIcon className="stroke-1" />`

From what I can tell these are hardcoded in the icons, so this doesn't take affect?

Please let me know if there is an alternative here? Thank you

**Comment by iwasrobbed** [comment]
+1 just came across this issue as well today, would love to be able to adjust this width as `2` is too thick for when icons are scaled up in size

**Comment by acomanescu** [comment]
Hi @tom-ads , the className you are adding gets applied to the svg element, not the path that contains the stroke value. You could add the class then select the element that has the `stroke-width` attribute, such as:

```html
<SearchIcon className="untitled-icon" />
```

```css
.untitled-icon [stroke-width] {
  stroke-width: 1;
}
```

This should target all elements. We could add a default classname to all elements so you won't need to manually add it.
